import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OnboardMasters",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/fontsource-inter@5.5.0/css/inter.min.css"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
